import 'package:flutter/material.dart';

enum Idioma { es, en, fr }

final ValueNotifier<Idioma> idiomaActual = ValueNotifier(Idioma.es);

const Map<Idioma, Map<String, String>> traducciones = {
  Idioma.es: {
    'menu_principal': 'Menú Principal',
    'catalogo_completo': 'Catálogo completo',
    'mis_favoritos': 'Mis Favoritos',
    'cerrar_sesion': 'Cerrar sesión',
    'buscar': 'Buscar...',
    'favoritos': 'Favoritos',
    'catalogo': 'Catálogo',
    'sin_favoritos': 'Aún no hay favoritos',
    'sin_peliculas': 'No se encontraron películas',
    'director': 'Director',
    'anio': 'Año de estreno',
    'valoracion': 'Valoración',
    'duracion': 'Duración',
    'reparto': 'Reparto',
    'sinopsis': 'Sinopsis Detallada',
    'idioma': 'Idioma',
    'espanol': 'Español',
    'ingles': 'Inglés',
    'frances': 'Francés',
    'mi_carrito': 'Mi Carrito',
    'anadir_carrito': 'Añadir al carrito',
    'anadir_seleccionadas': 'Añadir seleccionadas',
    'confirmar_compra': 'Confirmar Compra',
    'direccion_envio': 'Dirección de envío',
    'telefono': 'Teléfono',
    'cancelar': 'Cancelar',
    'confirmar_pedido': 'Confirmar Pedido',
    'carrito_vacio': 'El carrito está vacío',
    'anadir_mas': 'Añadir más',
    'comprar_ahora': 'Comprar Ahora',
    'anadir_peliculas': 'Añadir Películas',
    'mi_perfil': 'Mi Perfil',
    'campo_requerido': 'Campo requerido',
    'datos_cuenta': 'Datos de Cuenta',
    'historial_pedidos': 'Historial de Pedidos',
  },
  Idioma.en: {
    'menu_principal': 'Main Menu',
    'catalogo_completo': 'Full Catalog',
    'mis_favoritos': 'My Favorites',
    'cerrar_sesion': 'Log Out',
    'buscar': 'Search...',
    'favoritos': 'Favorites',
    'catalogo': 'Catalog',
    'sin_favoritos': 'No favorites yet',
    'sin_peliculas': 'No movies found',
    'director': 'Director',
    'anio': 'Release Year',
    'valoracion': 'Rating',
    'duracion': 'Duration',
    'reparto': 'Cast',
    'sinopsis': 'Detailed Synopsis',
    'idioma': 'Language',
    'espanol': 'Spanish',
    'ingles': 'English',
    'frances': 'French',
    'mi_carrito': 'My Cart',
    'anadir_carrito': 'Add to Cart',
    'anadir_seleccionadas': 'Add Selected',
    'confirmar_compra': 'Confirm Purchase',
    'direccion_envio': 'Shipping Address',
    'telefono': 'Phone Number',
    'cancelar': 'Cancel',
    'confirmar_pedido': 'Confirm Order',
    'carrito_vacio': 'Cart is empty',
    'anadir_mas': 'Add more',
    'comprar_ahora': 'Buy Now',
    'anadir_peliculas': 'Add Movies',
    'mi_perfil': 'My Profile',
    'campo_requerido': 'Required field',
    'datos_cuenta': 'Account Details',
    'historial_pedidos': 'Order History',
  },
  Idioma.fr: {
    'menu_principal': 'Menu Principal',
    'catalogo_completo': 'Catalogue Complet',
    'mis_favoritos': 'Mes Favoris',
    'cerrar_sesion': 'Se Déconnecter',
    'buscar': 'Rechercher...',
    'favoritos': 'Favoris',
    'catalogo': 'Catalogue',
    'sin_favoritos': 'Pas encore de favoris',
    'sin_peliculas': 'Aucun film trouvé',
    'director': 'Réalisateur',
    'anio': 'Année de sortie',
    'valoracion': 'Évaluation',
    'duracion': 'Durée',
    'reparto': 'Acteurs',
    'sinopsis': 'Synopsis Détaillé',
    'idioma': 'Langue',
    'espanol': 'Espagnol',
    'ingles': 'Anglais',
    'frances': 'Français',
    'mi_carrito': 'Mon Panier',
    'anadir_carrito': 'Ajouter au Panier',
    'anadir_seleccionadas': 'Ajouter la Sélection',
    'confirmar_compra': 'Confirmer l\'Achat',
    'direccion_envio': 'Adresse de Livraison',
    'telefono': 'Téléphone',
    'cancelar': 'Annuler',
    'confirmar_pedido': 'Confirmer la Commande',
    'carrito_vacio': 'Le panier est vide',
    'anadir_mas': 'Ajouter plus',
    'comprar_ahora': 'Acheter Maintenant',
    'anadir_peliculas': 'Ajouter des Films',
    'mi_perfil': 'Mon Profil',
    'campo_requerido': 'Champ requis',
    'datos_cuenta': 'Détails du Compte',
    'historial_pedidos': 'Historique des Commandes',
  }
};

String tr(String key) {
  return traducciones[idiomaActual.value]?[key] ?? key;
}
